import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { TestResult } from '../executor/types.js';
import type { ProjectInfo } from '../analyzer/types.js';
import type { TokenUsage } from '../../services/ai-client.js';
import { MarkdownBuilder } from './markdown-builder.js';
import { computeStats } from './summary-stats.js';
import { ensureDir } from '../../utils/fs.js';

export async function generateReport(
  results: TestResult[],
  projectInfo: ProjectInfo,
  reportPath: string,
  tokenUsage?: TokenUsage
): Promise<string> {
  const stats = computeStats(results);
  const passed = results.filter((r) => r.status === 'pass');
  const failed = results.filter((r) => r.status === 'fail');
  const blocked = results.filter((r) => r.status === 'blocked');

  const md = new MarkdownBuilder();

  md.h1('Test Report');

  md.h2('Summary');
  md.bullet(`Total Cases: ${stats.total}`);
  md.bullet(`Passed: ${stats.passed} (${stats.passRate}%)`);
  md.bullet(`Failed: ${stats.failed}`);
  md.bullet(`Blocked: ${stats.blocked}`);
  md.bullet(`Skipped: ${stats.skipped}`);
  md.bullet(`Duration: ${stats.totalDuration}s`);
  if (tokenUsage && tokenUsage.totalTokens > 0) {
    md.bullet(`Token Usage: Total ${tokenUsage.totalTokens} (Prompt: ${tokenUsage.promptTokens}, Completion: ${tokenUsage.completionTokens})`);
  }
  md.blankLine();

  // Category breakdown
  md.h2('Results by Category');
  md.table(
    ['Category', 'Total', 'Passed', 'Failed'],
    Object.entries(stats.byCategory).map(([cat, s]) => [
      cat,
      s.total.toString(),
      s.passed.toString(),
      s.failed.toString(),
    ]),
  );

  // Group by Feature
  const byFeature = new Map<string, TestResult[]>();
  for (const r of results) {
    if (!byFeature.has(r.feature)) {
      byFeature.set(r.feature, []);
    }
    byFeature.get(r.feature)!.push(r);
  }

  // Feature detailed breakdown
  for (const [feature, featureResults] of Array.from(byFeature.entries())) {
    md.h2(`Feature: ${feature}`);

    // Summary of this feature
    const fPassed = featureResults.filter(r => r.status === 'pass').length;
    const fFailed = featureResults.filter(r => r.status === 'fail').length;
    const fBlocked = featureResults.filter(r => r.status === 'blocked').length;
    const fSkipped = featureResults.filter(r => r.status === 'skipped').length;
    md.bullet(`Total Cases: ${featureResults.length} (Pass: ${fPassed}, Fail: ${fFailed}, Blocked: ${fBlocked}, Skipped: ${fSkipped})`);
    md.blankLine();

    // Generated Cases List for this Feature
    md.h3('Generated Test Cases');
    md.table(
      ['Case ID', 'Category', 'Description'],
      featureResults.map((r) => [r.caseId, r.category, r.description])
    );
    md.blankLine();

    // Execution Details (only show failures or blockages for brevity, or list all if wanted)
    // Here we list the failures specifically to make them prominent
    const fIssues = featureResults.filter(r => r.status === 'fail' || r.status === 'blocked');
    if (fIssues.length > 0) {
      md.h3('Failed / Blocked Execution Details');
      md.table(
        ['Case ID', 'Status', 'Error Detail'],
        fIssues.map(r => [r.caseId, r.status.toUpperCase(), r.errorDetail ?? ''])
      );
      md.blankLine();
    }
  }

  // Self-Healing Retry Summary
  const retriedCases = results.filter(r => r.wasRetried);
  if (retriedCases.length > 0) {
    md.h2('Self-Healing Retry Summary');
    const fixedCases = retriedCases.filter(r => r.status === 'pass');
    md.bullet(`Cases retried: ${retriedCases.length}`);
    md.bullet(`Successfully fixed: ${fixedCases.length}`);
    md.bullet(`Still failing after retry: ${retriedCases.length - fixedCases.length}`);
    const retryTokens = retriedCases.reduce(
      (sum, r) => sum + (r.retryTokenUsage?.totalTokens ?? 0),
      0,
    );
    if (retryTokens > 0) {
      md.bullet(`Retry token usage: ${retryTokens}`);
    }
    md.blankLine();
    md.table(
      ['Case ID', 'Category', 'Attempts', 'Final Status'],
      retriedCases.map(r => [
        r.caseId,
        r.category,
        String(r.retryAttempts ?? 0),
        r.status.toUpperCase(),
      ]),
    );
    md.blankLine();
  }

  // Project info
  md.h2('Project Info');
  md.bullet(`Path: ${projectInfo.projectPath}`);
  if (projectInfo.frontend.framework) {
    md.bullet(`Frontend: ${projectInfo.frontend.framework}`);
  }
  if (projectInfo.backend.framework) {
    md.bullet(`Backend: ${projectInfo.backend.framework}`);
  }
  md.bullet(`Features tested: ${projectInfo.features.length}`);
  md.blankLine();

  md.text(`---`);
  md.text(`Generated by ai-test at ${new Date().toISOString()}`);

  // Write report
  const absReportPath = path.resolve(reportPath);
  await ensureDir(path.dirname(absReportPath));
  await fs.writeFile(absReportPath, md.toString(), 'utf-8');

  return absReportPath;
}
